/*
    Inserting grocery data to file
 */
package semester_projecct;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Umaix
 */
public class JGrocery extends javax.swing.JFrame {

    /**
     * Creates new form JGrocery
     */
    public JGrocery() {
        initComponents();
        this.setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Jbutton3 = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        Jbutton4 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        Jbutton1 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Jbutton5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Stock = new javax.swing.JSpinner();
        menu = new javax.swing.JButton();
        Jbutton2 = new javax.swing.JLabel();
        Company = new javax.swing.JTextField();
        menu1 = new javax.swing.JButton();
        Export = new javax.swing.JButton();
        Export2 = new javax.swing.JButton();
        Export3 = new javax.swing.JButton();
        Export1 = new javax.swing.JButton();
        Export4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        Table1.setBackground(new java.awt.Color(204, 204, 204));
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Company", "Stock", "Price"
            }
        ));
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        Jbutton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jbutton3.setForeground(new java.awt.Color(255, 255, 255));
        Jbutton3.setText("Stock");

        Message.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        Message.setForeground(new java.awt.Color(255, 0, 0));

        Jbutton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jbutton4.setForeground(new java.awt.Color(255, 255, 255));
        Jbutton4.setText("Price");

        Price.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Jbutton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jbutton1.setForeground(new java.awt.Color(255, 255, 255));
        Jbutton1.setText("Name");

        Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Jbutton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jbutton5.setForeground(new java.awt.Color(255, 255, 255));
        Jbutton5.setText("ID ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/shopping-icon (3).png"))); // NOI18N
        jLabel1.setText("Grocery data");

        menu.setBackground(new java.awt.Color(0, 0, 204));
        menu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        menu.setText("Back");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        Jbutton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jbutton2.setForeground(new java.awt.Color(255, 255, 255));
        Jbutton2.setText("Company");

        Company.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        menu1.setBackground(new java.awt.Color(102, 102, 255));
        menu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menu1.setForeground(new java.awt.Color(255, 255, 255));
        menu1.setText("Grocery Stock");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Jbutton5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(Jbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Company))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(Jbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                            .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Jbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Jbutton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Name)
                                                .addComponent(Stock, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))
                                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jbutton5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Company, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jbutton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Export.setBackground(new java.awt.Color(0, 153, 153));
        Export.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Export.setForeground(new java.awt.Color(255, 255, 255));
        Export.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        Export.setText("ADD");
        Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportActionPerformed(evt);
            }
        });

        Export2.setBackground(new java.awt.Color(0, 153, 153));
        Export2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Export2.setForeground(new java.awt.Color(255, 255, 255));
        Export2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/upa.png"))); // NOI18N
        Export2.setText("Update");
        Export2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Export2ActionPerformed(evt);
            }
        });

        Export3.setBackground(new java.awt.Color(0, 153, 153));
        Export3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Export3.setForeground(new java.awt.Color(255, 255, 255));
        Export3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Actions-edit-delete-icon.png"))); // NOI18N
        Export3.setText("Delete");
        Export3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Export3ActionPerformed(evt);
            }
        });

        Export1.setBackground(new java.awt.Color(0, 153, 153));
        Export1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Export1.setForeground(new java.awt.Color(255, 255, 255));
        Export1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/insert.png"))); // NOI18N
        Export1.setText("Insert to file");
        Export1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Export1ActionPerformed(evt);
            }
        });

        Export4.setBackground(new java.awt.Color(0, 153, 153));
        Export4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Export4.setForeground(new java.awt.Color(255, 255, 255));
        Export4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/upa.png"))); // NOI18N
        Export4.setText("Update in File");
        Export4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Export4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Export, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Export2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Export3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Export1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Export4, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Export2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Export3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Export, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Export1)
                .addGap(18, 18, 18)
                .addComponent(Export4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Adding to the table
    private void ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportActionPerformed
        DefaultTableModel model = (DefaultTableModel) Table1.getModel(); 
        if(!Name.getText().trim().equals("")){
            model.addRow(new Object[] {ID.getText(),Name.getText(), Company.getText(), 
            (int) Stock.getValue(), Integer.parseInt(Price.getText())});
        }else{
            Message.setText("Product Data should not be left blank");
        }
    }//GEN-LAST:event_ExportActionPerformed
//Updating the table data
    private void Export2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Export2ActionPerformed
        Message.setText("");
        DefaultTableModel model = (DefaultTableModel) Table1.getModel();
        if(Table1.getSelectedRow()==-1){
            if(Table1.getSelectedColumn()==0){
                Message.setText("Table is Empty");
            }
            else{
                Message.setText("You must select a product");
            }
        }
        else{
            model.setValueAt(ID.getText(),Table1.getSelectedRow(),0);
            model.setValueAt(Name.getText(),Table1.getSelectedRow(),1);
            model.setValueAt(Company.getText(),Table1.getSelectedRow(),2);
            model.setValueAt(Stock.getValue(),Table1.getSelectedRow(),3);
            model.setValueAt(Price.getText(),Table1.getSelectedRow(),4);
        }
    }//GEN-LAST:event_Export2ActionPerformed
//Deleting the table data
    private void Export3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Export3ActionPerformed
        Message.setText("");
        DefaultTableModel model = (DefaultTableModel) Table1.getModel();
        if(Table1.getSelectedRow()==-1){
            if(Table1.getSelectedColumn()==0){
                Message.setText("Table is Empty");
            }
            else{
                Message.setText("You must select a product");
            }
        }
        else{
            model.removeRow(Table1.getSelectedRow());
        }
    }//GEN-LAST:event_Export3ActionPerformed
//Insert to file after setting data in table
    private void Export1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Export1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) Table1.getModel();
        if(!Name.getText().trim().equals("") && !ID.getText().trim().equals("")){
            try {
                File file = new File("Grocery.txt");
                BufferedWriter bw = new BufferedWriter(new FileWriter(file,true));
                for(int i=0; i<Table1.getRowCount(); i++){
                    for(int j=0; j<Table1.getColumnCount(); j++){
                        bw.append((String)Table1.getModel().getValueAt(i, j).toString() + " ");
                    }
                    bw.append(System.getProperty("line.separator"));
                }
                JOptionPane.showMessageDialog(rootPane, "Successfully Inserted data");
                bw.close();
                model.setRowCount(0);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, "Something went wrong please try gain later");
            }
        }
    }//GEN-LAST:event_Export1ActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        dispose();
        Admin obj = new Admin();
        obj.setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        try{                                         
            
            BufferedReader br;
            br = new BufferedReader(new FileReader("Grocery.txt"));
            String firstLine = br.readLine().trim();
            DefaultTableModel model = (DefaultTableModel) Table1.getModel();
            
            Object[] lines = br.lines().toArray();
            
            for (int i=0; i<lines.length; i++) {
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }
        }catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Something went wrong please try gain later");
        }catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Something went wrong please try gain later");
        }
    }//GEN-LAST:event_menu1ActionPerformed

    private void Export4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Export4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) Table1.getModel();
            try {
                File file = new File("Grocery.txt");
                BufferedWriter bw = new BufferedWriter(new FileWriter(file));
                bw.append((String)" Id " + " Name " + " Company " + " Stock "+ " Price " + " ");
                bw.append(System.getProperty("line.separator"));
                for(int i=0; i<Table1.getRowCount(); i++){
                    for(int j=0; j<Table1.getColumnCount(); j++){
                        bw.append((String)Table1.getModel().getValueAt(i, j).toString() + " ");
                    }
                    bw.append(System.getProperty("line.separator"));
                }
                JOptionPane.showMessageDialog(rootPane, "Successfully Inserted data");
                bw.close();
                model.setRowCount(0);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, "Something went wrong please try gain later");
            }
    }//GEN-LAST:event_Export4ActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        DefaultTableModel model = (DefaultTableModel) Table1.getModel();
        ID.setText(model.getValueAt(Table1.getSelectedRow(), 0).toString());
        Name.setText(model.getValueAt(Table1.getSelectedRow(), 1).toString());
        Company.setText(model.getValueAt(Table1.getSelectedRow(), 2).toString());
        Price.setText(model.getValueAt(Table1.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_Table1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JGrocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JGrocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JGrocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JGrocery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JGrocery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Company;
    private javax.swing.JButton Export;
    private javax.swing.JButton Export1;
    private javax.swing.JButton Export2;
    private javax.swing.JButton Export3;
    private javax.swing.JButton Export4;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel Jbutton1;
    private javax.swing.JLabel Jbutton2;
    private javax.swing.JLabel Jbutton3;
    private javax.swing.JLabel Jbutton4;
    private javax.swing.JLabel Jbutton5;
    private javax.swing.JLabel Message;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Price;
    private javax.swing.JSpinner Stock;
    private javax.swing.JTable Table1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menu;
    private javax.swing.JButton menu1;
    // End of variables declaration//GEN-END:variables
}
