/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semester_projecct;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Umaix
 */
public class JHomeAppliances extends javax.swing.JFrame {

    /**
     * Creates new form JHomeAppliances
     */
    public JHomeAppliances() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Jbutton11 = new javax.swing.JLabel();
        Message2 = new javax.swing.JLabel();
        Jbutton12 = new javax.swing.JLabel();
        Price2 = new javax.swing.JTextField();
        ID2 = new javax.swing.JTextField();
        Jbutton13 = new javax.swing.JLabel();
        Name2 = new javax.swing.JTextField();
        Jbutton14 = new javax.swing.JLabel();
        Jbutton15 = new javax.swing.JLabel();
        Company2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        stock = new javax.swing.JSpinner();
        menu = new javax.swing.JButton();
        menu1 = new javax.swing.JButton();
        Export2 = new javax.swing.JButton();
        Export3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        Export1 = new javax.swing.JButton();
        Export = new javax.swing.JButton();
        Export4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        Jbutton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jbutton11.setForeground(new java.awt.Color(255, 255, 255));
        Jbutton11.setText("Stock");

        Message2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        Message2.setForeground(new java.awt.Color(255, 0, 0));

        Jbutton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jbutton12.setForeground(new java.awt.Color(255, 255, 255));
        Jbutton12.setText("Price");

        Price2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ID2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Jbutton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jbutton13.setForeground(new java.awt.Color(255, 255, 255));
        Jbutton13.setText("Name");

        Name2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Jbutton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jbutton14.setForeground(new java.awt.Color(255, 255, 255));
        Jbutton14.setText("ID ");

        Jbutton15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jbutton15.setForeground(new java.awt.Color(255, 255, 255));
        Jbutton15.setText("Company");

        Company2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/TV_1.png"))); // NOI18N
        jLabel3.setText("Home App. data");

        menu.setBackground(new java.awt.Color(0, 0, 204));
        menu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        menu.setText("Back");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        menu1.setBackground(new java.awt.Color(102, 102, 255));
        menu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menu1.setForeground(new java.awt.Color(255, 255, 255));
        menu1.setText("Stock");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Jbutton13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Name2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Jbutton14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ID2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(Jbutton12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Price2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Jbutton11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stock))
                    .addComponent(Message2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(Jbutton15, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Company2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(menu))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbutton14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jbutton13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Company2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jbutton15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbutton11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jbutton12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(Message2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu)
                .addContainerGap())
        );

        Export2.setBackground(new java.awt.Color(0, 153, 153));
        Export2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Export2.setForeground(new java.awt.Color(255, 255, 255));
        Export2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/upa.png"))); // NOI18N
        Export2.setText("Update");
        Export2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Export2ActionPerformed(evt);
            }
        });

        Export3.setBackground(new java.awt.Color(0, 153, 153));
        Export3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Export3.setForeground(new java.awt.Color(255, 255, 255));
        Export3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Actions-edit-delete-icon.png"))); // NOI18N
        Export3.setText("Delete");
        Export3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Export3ActionPerformed(evt);
            }
        });

        Table2.setBackground(new java.awt.Color(204, 204, 204));
        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Company Name", "Stock", "Price"
            }
        ));
        Table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table2);

        Export1.setBackground(new java.awt.Color(0, 153, 153));
        Export1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Export1.setForeground(new java.awt.Color(255, 255, 255));
        Export1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/insert.png"))); // NOI18N
        Export1.setText("Insert to file");
        Export1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Export1ActionPerformed(evt);
            }
        });

        Export.setBackground(new java.awt.Color(0, 153, 153));
        Export.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Export.setForeground(new java.awt.Color(255, 255, 255));
        Export.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        Export.setText("ADD");
        Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportActionPerformed(evt);
            }
        });

        Export4.setBackground(new java.awt.Color(0, 153, 153));
        Export4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Export4.setForeground(new java.awt.Color(255, 255, 255));
        Export4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/upa.png"))); // NOI18N
        Export4.setText("Update in File");
        Export4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Export4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(Export, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Export2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Export3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Export1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Export4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Export2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Export3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Export, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Export1)
                .addGap(18, 18, 18)
                .addComponent(Export4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Export2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Export2ActionPerformed
        Message2.setText("");
        DefaultTableModel model = (DefaultTableModel) Table2.getModel();
        if(Table2.getSelectedRow()==-1){
            if(Table2.getSelectedColumn()==0){
                Message2.setText("Table is Empty");
            }
            else{
                Message2.setText("You must select a product");
            }
        }
        else{
            model.setValueAt(ID2.getText(),Table2.getSelectedRow(),0);
            model.setValueAt(Name2.getText(),Table2.getSelectedRow(),1);
            model.setValueAt(Company2.getText(),Table2.getSelectedRow(),2);
            model.setValueAt((int) stock.getValue(),Table2.getSelectedRow(),3);
            model.setValueAt(Price2.getText(),Table2.getSelectedRow(),4);

        }
    }//GEN-LAST:event_Export2ActionPerformed

    private void Export3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Export3ActionPerformed
        Message2.setText("");
        DefaultTableModel model = (DefaultTableModel) Table2.getModel();
        if(Table2.getSelectedRow()==-1){
            if(Table2.getSelectedColumn()==0){
                Message2.setText("Table is Empty");
            }
            else{
                Message2.setText("You must select a product");
            }
        }
        else{
            model.removeRow(Table2.getSelectedRow());
        }
    }//GEN-LAST:event_Export3ActionPerformed

    private void Export1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Export1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) Table2.getModel();
        if(!Name2.getText().trim().equals("") && !ID2.getText().trim().equals("") && !Company2.getText().trim().equals("")){
            try {
                File file = new File("Home Appliances.txt");
                BufferedWriter bw = new BufferedWriter(new FileWriter(file,true));
                for(int i=0; i<Table2.getRowCount(); i++){
                    for(int j=0; j<Table2.getColumnCount(); j++){
                        bw.append((String)Table2.getModel().getValueAt(i, j).toString() + " ");
                    }
                    bw.append(System.getProperty("line.separator"));
                }
                JOptionPane.showMessageDialog(rootPane, "Successfully Inserted data");
                bw.close();
                model.setRowCount(0);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, "Something went wrong please try gain later");
            }
        }
    }//GEN-LAST:event_Export1ActionPerformed

    private void ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportActionPerformed
        DefaultTableModel model = (DefaultTableModel) Table2.getModel();
        if(!Name2.getText().trim().equals("")){
            model.addRow(new Object[] {ID2.getText(),Name2.getText(), Company2.getText(),
                         stock.getValue(), Integer.parseInt(Price2.getText())});
        }else{
            Message2.setText("Product Data should not be left blank");
        }
    }//GEN-LAST:event_ExportActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        dispose();
        Admin obj = new Admin();
        obj.setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        try{

            BufferedReader br;
            br = new BufferedReader(new FileReader("Home Appliances.txt"));
            String firstLine = br.readLine().trim();
            DefaultTableModel model = (DefaultTableModel) Table2.getModel();

            Object[] lines = br.lines().toArray();

            for (int i=0; i<lines.length; i++) {
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }
        }catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Something went wrong please try gain later");
        }catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Something went wrong please try gain later");
        }
    }//GEN-LAST:event_menu1ActionPerformed

    private void Export4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Export4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) Table2.getModel();
        try {
            File file = new File("Home Appliances.txt");
            BufferedWriter bw = new BufferedWriter(new FileWriter(file));
            bw.append((String)" Id " + " Name " + " Company " + " Stock "+ " Price " + " ");
            bw.append(System.getProperty("line.separator"));
            for(int i=0; i<Table2.getRowCount(); i++){
                for(int j=0; j<Table2.getColumnCount(); j++){
                    bw.append((String)Table2.getModel().getValueAt(i, j).toString() + " ");
                }
                bw.append(System.getProperty("line.separator"));
            }
            JOptionPane.showMessageDialog(rootPane, "Successfully Inserted data");
            bw.close();
            model.setRowCount(0);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Something went wrong please try gain later");
        }
    }//GEN-LAST:event_Export4ActionPerformed

    private void Table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table2MouseClicked
        DefaultTableModel model = (DefaultTableModel) Table2.getModel();
        ID2.setText(model.getValueAt(Table2.getSelectedRow(), 0).toString());
        Name2.setText(model.getValueAt(Table2.getSelectedRow(), 1).toString());
        Company2.setText(model.getValueAt(Table2.getSelectedRow(), 2).toString());
        Price2.setText(model.getValueAt(Table2.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_Table2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JHomeAppliances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JHomeAppliances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JHomeAppliances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JHomeAppliances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JHomeAppliances().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Company2;
    private javax.swing.JButton Export;
    private javax.swing.JButton Export1;
    private javax.swing.JButton Export2;
    private javax.swing.JButton Export3;
    private javax.swing.JButton Export4;
    private javax.swing.JTextField ID2;
    private javax.swing.JLabel Jbutton11;
    private javax.swing.JLabel Jbutton12;
    private javax.swing.JLabel Jbutton13;
    private javax.swing.JLabel Jbutton14;
    private javax.swing.JLabel Jbutton15;
    private javax.swing.JLabel Message2;
    private javax.swing.JTextField Name2;
    private javax.swing.JTextField Price2;
    private javax.swing.JTable Table2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JButton menu;
    private javax.swing.JButton menu1;
    private javax.swing.JSpinner stock;
    // End of variables declaration//GEN-END:variables
}
